# .github/workflows/main.yml
# For this to workout it is necessary to have:
# - A Project on GCP;
# - Google Drive API activated on Project;
# - A Google Service Account that has access to GDrive folder;
# - Secrets setted on GitHub repository.
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }} # Google service account credentials base64 encoded -> base64 secrets.json -w0 (bash)
          filename: "tcc-doc/main.pdf"
          folderId: ${{ secrets.FOLDER_ID }} # https://drive.google.com/drive/u/0/folders/FOLDER_ID
          name: "TCC_Thiago_v${{ steps.date.outputs.date }}.pdf" # Update every new version
          overwrite: "false" # False in case I forget something